fase-1/main.py
from flask import Flask, url_for, render_template

# inicialização
app = Flask(__name__)

#rotas
@app.route("/")
def home():
    titulo = "Gestão de Usuários"
    usuários = [
        {"name": "Jânderson", "user_active": True},
        {"name": "Jonas", "user_active": False},
        {"name": "Maria", "user_active": True},
        {"name": "Socorro", "user_active": False}
    ]
    return render_template('index.html', title = titulo, users = usuários)


@app.route("/about")
def pag_about():
    return f"""
        <h1>Meu nome é Jânderson</h1>
        <p>eu sou programador Python</p>
        <a href='{url_for('home')}'>retornar ao home</a>
    """


# execução
app.run(debug = True)

main.py
from flask import Flask
from routes.home import home_route
from routes.client import client_route
# inicialização
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(client_route, url_prefix='/clientes')

# execução
app.run(debug = True)

routes/client.py
from flask import Blueprint, render_template, request
from database.client import CLIENTES

client_route = Blueprint('client', __name__)

@client_route.route('/')
def list_clients():
    return render_template('list_clients.html', clients = CLIENTES)


@client_route.route('/', methods=['POST'])
def insert_client():
    """inserir cliente"""
    data = request.json
    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "name": data('name'),
        "email": data('email'),
    }
    CLIENTES.append(novo_usuario)
    return {"client": novo_usuario}


@client_route.route('/new')
def form_client():
    """ formulário para cadastrar cliente """
    return render_template('form_client.html')


@client_route.route('/<int:client_id>')
def details_client(client_id):
    """ exibir detalhes do cliente """
    return render_template('details_client.html')


@client_route.route('/<int:client_id>/edit')
def form_edit_client(client_id):
    """ formulário para editar um cliente """
    return render_template('form_edit_client.html')


@client_route.route('/<int:client_id>/update', methods=['PUT'])
def update_client(client_id):
    """ atualizar informações do cliente """
    pass


@client_route.route('/<int:client_id>/delete', methods=['PUT'])
def delete_client(client_id):
    """ deletar informações do cliente """
    pass

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_client.html
    <form class="c-form" action="{{ url_for('client.insert_client') }}" method="POST">
        <div class="mb-3">
            <label class="form-label">Nome</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="text" class="form-control" name="email">
        </div>

        <button type="submit" class="btn btn-primary">Adicionar cliente</button>
    </form>

templates/index.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap demo</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{{url_for('static', filename='css/app.css') }}">
    </head>
    <body>
        <div class="container">

            <h1>Gestão de clientes</h1>
            <!-- Formulário add cliente -->
            <div c-container="{{ url_for('client.form_client')}}"></div>
            <hr>
            <!-- Lista de clientes -->
            <h2>Lista de cliente</h2>
            <div c-container="{{ url_for('client.list_clients') }}"></div>
            
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="{{url_for('static', filename='js/cru.js') }}"></script>
    </body>
</html>

templates/item_client.html
<tr>
    <th scope="row">{{ client.id }}</th>
    <td>{{ client.name }}</td>
    <td>{{ client.email }}</td>
    <td>
        <button class="btn btn-primary">Editar</button>
        <button class="btn btn-danger">Deletar</button>
    </td>
</tr>

templates/list_clients.html
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
            {% include 'item_client.html' %}
        {% endfor %}
    </tbody>
    </table>